client_config_backend: settings
client_config:
  client_id: 783152113975-ltbsq8lc8io5h0mqsqpdse288etvip6q.apps.googleusercontent.com
  client_secret: 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
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
